package com.zakgof.korender

import java.awt.event.KeyEvent.*

internal val KEY_MAPPING = mapOf(
    VK_A to "A",
    VK_B to "B",
    VK_C to "C",
    VK_D to "D",
    VK_E to "E",
    VK_F to "F",
    VK_G to "G",
    VK_H to "H",
    VK_I to "I",
    VK_J to "J",
    VK_K to "K",
    VK_L to "L",
    VK_M to "M",
    VK_N to "N",
    VK_O to "O",
    VK_P to "P",
    VK_Q to "Q",
    VK_R to "R",
    VK_S to "S",
    VK_T to "T",
    VK_U to "U",
    VK_V to "V",
    VK_W to "W",
    VK_X to "X",
    VK_Y to "Y",
    VK_Z to "Z",
    VK_0 to "0",
    VK_1 to "1",
    VK_2 to "2",
    VK_3 to "3",
    VK_4 to "4",
    VK_5 to "5",
    VK_6 to "6",
    VK_7 to "7",
    VK_8 to "8",
    VK_9 to "9",
    VK_ESCAPE to "ESC",
    VK_F1 to "F1",
    VK_F2 to "F2",
    VK_F3 to "F3",
    VK_F4 to "F4",
    VK_F5 to "F5",
    VK_F6 to "F6",
    VK_F7 to "F7",
    VK_F8 to "F8",
    VK_F9 to "F9",
    VK_F10 to "F10",
    VK_F11 to "F11",
    VK_F12 to "F12",
    VK_PRINTSCREEN to "PRINTSCREEN",
    VK_DELETE to "DEL",
    VK_HOME to "HOME",
    VK_END to "END",
    VK_PAGE_UP to "PGUP",
    VK_PAGE_DOWN to "PGDOWN",
    VK_DEAD_TILDE to "~",
    VK_TAB to "TAB",
    VK_CAPS_LOCK to "CAPSLOCK",
    VK_UP to "UP",
    VK_DOWN to "DOWN",
    VK_LEFT to "LEFT",
    VK_RIGHT to "RIGHT",
)