package com.zakgof.korender.impl.gl

expect object GLConstants {
    val GL_LEQUAL: GLConstant
    val GL_GEQUAL: GLConstant
    val GL_DEPTH_BUFFER_BIT: GLConstant
    val GL_COLOR_BUFFER_BIT: GLConstant
    val GL_TRIANGLES: GLConstant
    val GL_ONE: GLConstant
    val GL_ONE_MINUS_SRC_ALPHA: GLConstant
    val GL_BYTE: GLConstant
    val GL_UNSIGNED_BYTE: GLConstant
    val GL_SHORT: GLConstant
    val GL_UNSIGNED_SHORT: GLConstant
    val GL_INT: GLConstant
    val GL_UNSIGNED_INT: GLConstant
    val GL_FLOAT: GLConstant
    val GL_FRONT: GLConstant
    val GL_BACK: GLConstant
    val GL_CULL_FACE: GLConstant
    val GL_DEPTH_TEST: GLConstant
    val GL_BLEND: GLConstant
    val GL_TEXTURE_2D: GLConstant
    val GL_DEPTH_COMPONENT: GLConstant
    val GL_RED: GLConstant
    val GL_RGB: GLConstant
    val GL_RGBA: GLConstant
    val GL_VENDOR: GLConstant
    val GL_RENDERER: GLConstant
    val GL_VERSION: GLConstant
    val GL_NEAREST: GLConstant
    val GL_LINEAR: GLConstant
    val GL_LINEAR_MIPMAP_LINEAR: GLConstant
    val GL_TEXTURE_MAG_FILTER: GLConstant
    val GL_TEXTURE_MIN_FILTER: GLConstant
    val GL_TEXTURE_WRAP_S: GLConstant
    val GL_TEXTURE_WRAP_T: GLConstant
    val GL_REPEAT: GLConstant
    val GL_TEXTURE_3D: GLConstant
    val GL_TEXTURE_WRAP_R: GLConstant
    val GL_CLAMP_TO_EDGE: GLConstant
    val GL_TEXTURE_CUBE_MAP: GLConstant
    val GL_TEXTURE_CUBE_MAP_POSITIVE_X: GLConstant
    val GL_TEXTURE_CUBE_MAP_NEGATIVE_X: GLConstant
    val GL_TEXTURE_CUBE_MAP_POSITIVE_Y: GLConstant
    val GL_TEXTURE_CUBE_MAP_NEGATIVE_Y: GLConstant
    val GL_TEXTURE_CUBE_MAP_POSITIVE_Z: GLConstant
    val GL_TEXTURE_CUBE_MAP_NEGATIVE_Z: GLConstant
    val GL_TEXTURE0: GLConstant
    val GL_DEPTH_COMPONENT16: GLConstant
    val GL_DEPTH_COMPONENT24: GLConstant
    val GL_DEPTH_COMPONENT32: GLConstant
    val GL_TEXTURE_COMPARE_MODE: GLConstant
    val GL_TEXTURE_COMPARE_FUNC: GLConstant
    val GL_MIRRORED_REPEAT: GLConstant
    val GL_ARRAY_BUFFER: GLConstant
    val GL_ELEMENT_ARRAY_BUFFER: GLConstant
    val GL_STATIC_DRAW: GLConstant
    val GL_DYNAMIC_DRAW: GLConstant
    val GL_COMPILE_STATUS: GLConstant
    val GL_LINK_STATUS: GLConstant
    val GL_ACTIVE_UNIFORMS: GLConstant
    val GL_VERTEX_SHADER: GLConstant
    val GL_FRAGMENT_SHADER: GLConstant
    val GL_RGBA32F: GLConstant
    val GL_FRAMEBUFFER: GLConstant
    val GL_COLOR_ATTACHMENT0: GLConstant
    val GL_DEPTH_ATTACHMENT: GLConstant
    val GL_FRAMEBUFFER_COMPLETE: GLConstant
    val GL_R8: GLConstant
    val GL_R16: GLConstant
    val GL_RG8: GLConstant
    val GL_RG16: GLConstant
    val GL_RG: GLConstant
    val GL_TEXTURE_MAX_ANISOTROPY: GLConstant
    val GL_MAX_TEXTURE_MAX_ANISOTROPY: GLConstant
    val GL_TEXTURE_CUBE_MAP_SEAMLESS: GLConstant
    val GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS: GLConstant
    val GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES: GLConstant
    val GL_UNIFORM_OFFSET: GLConstant
    val GL_UNIFORM_BLOCK_DATA_SIZE: GLConstant
    val GL_UNIFORM_BUFFER: GLConstant
    val GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT: GLConstant
    val GL_MAX_UNIFORM_BUFFER_BINDINGS: GLConstant
    val GL_MAX_UNIFORM_BLOCK_SIZE: GLConstant
}